version: 2

run:
  timeout: 5m

linters-settings:
  gosec:
    excludes:
      - G115

linters:
  default: all

  disable:
    # We don't have high-performance requirements at this moment, so sacrificing
    # the code readability for marginal performance gains is not worth it.
    - prealloc

    # New linters that require a lot of codebase churn and noise, but perhaps we can enable them in the future.
    - nlreturn
    - wrapcheck
    - errorlint

    # Unfortunately, we use globals due to how spf13/cobra works.
    - gochecknoglobals

    # Style linters that are total nuts.
    - wsl
    - funlen
    - tagliatelle
    - tagalign

    # Enough parallelism for now.
    - paralleltest

    # Ill-based assumptions about identifiers like fmt.Println without taking context into account.
    - forbidigo

    # Advantages of using t.Helper() are too small to waste developer's cognitive stamina on it.
    - thelper

    # Too restrictive defaults, plus there's already a gocyclo linter in place.
    - cyclop

    # Gives false positives for textbook examples[1][2]
    # [1]: https://github.com/charithe/durationcheck/issues/7
    # [2]: https://golang.org/pkg/time/ (see "To convert an integer number of units to a Duration, multiply:")
    - durationcheck

    # No way to disable the "exported" check for the whole project[1]
    # [1]: https://github.com/mgechev/revive/issues/244#issuecomment-560512162
    - revive

    # Needs package whitelists
    - depguard

    # We don't care about some of the errors
    - errcheck

    # It's OK to have "magic" numbers in things like time.Sleep()
    - mnd

    # fmt.Sprintf() looks nicer than string concatenation
    - perfsprint

    # It's OK to have variables like vm, ip, n, etc.
    - varnamelen

    # It's OK to have dynamic errors since we're not a library
    - err113

    # Some functions are complex indeed
    - maintidx

    # Even in Rust you can get away with partial matching,
    # so make sure that the linter respects the programmer's
    # intent expressed in the form of "default" case.
    - exhaustruct

issues:
  # Don't hide multiple issues that belong to one class since GitHub annotations can handle them all nicely.
  max-issues-per-linter: 0
  max-same-issues: 0
